apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: openshift-logging 
spec:
  channel: "4.6" 
  name: cluster-logging
  source: my-operator-catalog
  sourceNamespace: openshift-marketplace
