apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: "{{ infrastructureID }}"
  name: "{{ infrastructureID }}-infra-1b"
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: "{{ infrastructureID }}"
      machine.openshift.io/cluster-api-machineset: "{{ infrastructureID }}-infra-1a" 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: "{{ infrastructureID }}" 
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra 
        machine.openshift.io/cluster-api-machineset: "{{ infrastructureID }}-infra-1a"
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      providerSpec:
        value:
          ami:
            id: ami-a45ab1d5 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: "{{ infrastructureID }}-infra-profile"  # Need to change this 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-gov-east-1a
            region: us-gov-east-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - "{{ infrastructureID }}-infra-sg"  # Change
          subnet:
            filters:
              - name: tag:Name
                values:
                  - "{{ infrastructureID }}-private-us-gov-east-1a"
          tags:
            - name: "kubernetes.io/cluster/{{ infrastructureID }}"
              value: owned
          userDataSecret:
            name: infra-user-data   # Change
