apiVersion: "autoscaling.openshift.io/v1beta1"
kind: "MachineAutoscaler"
metadata:
  name: "{{ infrastructureID }}-worker-us-gov-east-1b" 
  namespace: "openshift-machine-api"
spec:
  minReplicas: 1 
  maxReplicas: 3
  scaleTargetRef: 
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet 
    name: "{{ infrastructureID }}-worker-us-gov-east-1b"