apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: "{{ infrastructureID }}"
  name: "{{ infrastructureID }}-worker-1b"
  namespace: openshift-machine-api
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: "{{ infrastructureID }}"
      machine.openshift.io/cluster-api-machineset: "{{ infrastructureID }}-worker-1b" 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: "{{ infrastructureID }}" 
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: "{{ infrastructureID }}-worker-1b"
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "" 
      providerSpec:
        value:
          ami:
            id: ami-a45ab1d5 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: "{{ infrastructureID }}-worker-profile"  # Need to change this 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: us-gov-east-1b
            region: us-gov-east-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - "{{ infrastructureID }}-worker-sg"  # Change
          subnet:
            filters:
              - name: tag:Name
                values:
                  - "{{ infrastructureID }}-private-us-gov-east-1b"
          tags:
            - name: "kubernetes.io/cluster/{{ infrastructureID }}"
              value: owned
          userDataSecret:
            name: worker-user-data
