apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 99-worker-unqualified-search-registries
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,dW5xdWFsaWZpZWQtc2VhcmNoLXJlZ2lzdHJpZXMgPSBbJ21pcnJvci1vY3A0LnNieDIuZHNvLm5jcHMudXMtY2VydC5nb3YnLCAnZG9ja2VyLmFydGlmYWN0b3J5LmFwcHMuZWNpY2QuZHNvLm5jcHMudXMtY2VydC5nb3YnXQoK
        filesystem: root
        mode: 0420
        path: /etc/containers/registries.d/99-worker-unqualified-search-registries.conf
