---
# vars file for ops_cluster_autoscaling

machine_autoscaler_files:
  - "{{ role_path }}/templates/clusterWorkerScaler-1a.j2"
  - "{{ role_path }}/templates/clusterWorkerScaler-1b.j2"
  - "{{ role_path }}/templates/clusterWorkerScaler-1c.j2"
